name: CI

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
        - 28.2
        - 29.4
        - 30.1
        # - snapshot
    env:
      EMACS_VERSION: ${{ matrix.emacs_version }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v2

    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - uses: conao3/setup-cask@master

    - name: Print GitHub event
      run: cat "$GITHUB_EVENT_PATH"

    - name: Print Emacs version and environment variables
      run: |
        env
        emacs --version

    - name: Test
      run: |
        make test
